GET http://localhost:8080/
Accept: application/json

###

GET http://localhost:8080/api/employees
Accept: application/json

###

GET http://localhost:8080/api/employees/1
Accept: application/json

###

GET http://localhost:8080/api/employees?page=1&size=5
Accept: application/json

###

GET http://localhost:8080/api/employees?part=Jack
Accept: application/json

###

POST http://localhost:8080/api/employees
Content-Type: application/json

{
  "name": "Jack Doe"
}

###

POST http://localhost:8080/api/employees
Content-Type: application/json

{
  "name": ""
}

###
PUT http://localhost:8080/api/employees/1
Content-Type: application/json

{
  "name": "Jack Jack Jack Doe"
}

###

DELETE http://localhost:8080/api/employees/25
Accept: application/json

###

GET http://localhost:8080/actuator

###

GET http://localhost:8080/actuator/info

###

GET http://localhost:8080/actuator/health

###

GET http://localhost:8080/actuator/scheduledtasks

###

GET http://localhost:8080/actuator/liquibase

###

GET http://localhost:8080/actuator/env

###

GET http://localhost:8080/actuator/caches